### PR TITLE
[WIP] CoreAlert ->>>><&& CoreCard

### PR DESCRIPTION
**Pull request by hector-chauran**
test

### CODE REVIEW

**Comment by hector-chauran** [comment]
@hector-test HELLO!

**Comment by hector-chauran** [comment]
@hector-test .

**Comment by hector-chauran** [comment]
@hector-test test

**Comment by hector-test** [comment]
@hector-chauran test

**Comment by hector-chauran** [comment]
@hector-test .

**Comment by hector-chauran** [comment]
@hector-chauran .

**Comment by hector-chauran** [comment]
@hector-chauran .

**Comment by hector-chauran** [comment]
@hector-test .

**Comment by hector-chauran** [comment]
@hector-test  .

**Comment by hector-chauran** [comment]
@hector-test-2 @hector-test

**Pull request closed without merging**
